# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% ../00_core.ipynb 1
from testing_grounds.core import *
import unittest

# %% ../00_core.ipynb 4
import fastcore.test as ft

# %% ../00_core.ipynb 6
class CoreTester(unittest.TestCase):

# %% ../00_core.ipynb 8
    def test_addition():
        ft.test_eq(addition(1,2), 3)
        ft.test_eq(addition(-1,0), -1)