# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.
# %% ../00_core.ipynb 3
from fastcore.test import *

from testing_grounds.core import *
import unittest

class CoreTester(unittest.TestCase):