# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.
		# %% ../00_core.ipynb 3
		from fastcore.test import *

from testing_grounds.core import *
import unittest

class CoreTester(unittest.TestCase):
	# %% ../00_core.ipynb 6
	def test_addition(self):
	test_eq(addition(1,2), 3)
	test_eq(addition(-1,0), -1)