# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% ../00_core.ipynb 2
from testing_grounds.core import *
import unittest

# %% ../00_core.ipynb 5
import fastcore.test as ft

# %% ../00_core.ipynb 7
class CoreTester(unittest.TestCase):

# %% ../00_core.ipynb 9
    def test_addition(self):
        ft.test_eq(addition(1,2), 3)
        ft.test_eq(addition(-1,0), -1)
        ft.test_eq(addition(1,2), 3)
