# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto 0
__all__ = None

# %% ../00_core.ipynb 4
from fastcore.test import *


# %% ../00_core.ipynb 5
	def test_directive(self):
		#|test directive Core unittest.TestCase

# %% ../00_core.ipynb 7
	def test_addition(self):
		test_eq(addition(1,2), 3)
		test_eq(addition(-1,0), -1)